version: '3'
services:
  app:
    image: ticketsapp:0.0.1
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_DATABASE=ticketsdb

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ticketsdb
    volumes:
      - node_postgres:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  node_postgres: